# .github/workflows/main.yml
name: Preprocessing CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run preprocessing script
        run: python preprocessing/automate_wahyu.py

      - name: Upload processed data artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-dataset
          path: preprocessing/Kelayakan-pendidikan-indonesia_preprocessing/